version: '3.1'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    env_file:
      - ".env"
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgresql:/var/lib/postgresql

  django:
    container_name: djangoproject
    build:
      context: .
    command: python django_app.py runserver 0.0.0.0:8000 --noreload
    ports:
      - 8000:8000
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
    volumes:
      - ./postgresql:/var/lib/postgresql
    # Бот стартует после запуска базы
    depends_on:
      - db

  tgbot:
    container_name: shop_bot
    build:
      context: .
    command: python app.py
    volumes:
      - .:/src
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    # Бот стартует после запуска базы
    depends_on:
      - db
      - django

networks:
  botnet:
    driver: bridge