# Generated by Django 3.2.3 on 2021-06-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0002_auto_20210607_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='channels',
            name='channel_link',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Канал'),
        ),
    ]
