# Generated by Django 3.2.3 on 2021-06-09 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0003_auto_20210607_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referrer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Привел пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Баллы'),
        ),
    ]
