# Generated by Django 3.2.3 on 2021-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0004_auto_20210609_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_code', models.CharField(max_length=200, null=True, unique=True, verbose_name='Код приглашения')),
            ],
            options={
                'verbose_name': 'Код приглашения',
                'verbose_name_plural': 'Приглашения',
            },
        ),
        migrations.DeleteModel(
            name='Channels',
        ),
    ]
