# Generated by Django 3.2.3 on 2021-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0006_shop_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
