# Generated by Django 3.2.3 on 2021-06-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0007_referral_referral_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес доставки'),
        ),
    ]
