# Generated by Django 3.2.3 on 2021-06-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0009_alter_purchase_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Привел пользователь'),
        ),
    ]
