# Generated by Django 3.2.3 on 2021-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0010_alter_referral_referrer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
