# Generated by Django 3.2.3 on 2021-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0012_auto_20210616_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='item',
            field=models.CharField(max_length=250),
        ),
    ]
