# Generated by Django 3.2.3 on 2021-06-19 20:08

from django.db import migrations, models
import django_project.telega_bot.usersmanage.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0015_alter_purchase_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(on_delete=models.SET(django_project.telega_bot.usersmanage.models.get_sentinel_user), to='usersmanage.user', verbose_name='Покупатель'),
        ),
    ]
