# Generated by Django 3.2.3 on 2021-06-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0017_auto_20210619_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
