# Generated by Django 3.2.3 on 2021-06-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0018_alter_purchase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=12, max_length=100, verbose_name='Username Телеграм'),
            preserve_default=False,
        ),
    ]
